opt_scop LIKE '%游客%' OR
opt_scop LIKE '%景区%' OR
opt_scop LIKE '%旅行社%' OR
opt_scop LIKE '%导游%' OR
opt_scop LIKE '%门票%' OR
opt_scop LIKE '%旅居%' OR
opt_scop LIKE '%纪念品%' OR
opt_scop LIKE '%客运%' OR
opt_scop LIKE '%轨道交通%' OR
opt_scop LIKE '%出租车%' OR
opt_scop LIKE '%旅游用车%' OR
opt_scop LIKE '%旅游船舶%' OR
opt_scop LIKE '%飞行器的租赁%' OR
opt_scop LIKE '%房车%' OR
opt_scop LIKE '%航空%' OR
opt_scop LIKE '%铁路%' OR
opt_scop LIKE '%船舶%' OR
opt_scop LIKE '%机场%' OR
opt_scop LIKE '%旅馆%' OR
opt_scop LIKE '%农家%' OR
opt_scop LIKE '%露营%' OR
opt_scop LIKE '%营地%' OR
opt_scop LIKE '%休养所%' OR
opt_scop LIKE '%餐饮%' OR
opt_scop LIKE '%饭馆%' OR
opt_scop LIKE '%茶馆%' OR
opt_scop LIKE '%咖啡%' OR
opt_scop LIKE '%冷饮%' OR
opt_scop LIKE '%自然保护区%' OR
opt_scop LIKE '%动物园%' OR
opt_scop LIKE '%海洋馆%' OR
opt_scop LIKE '%植物园%' OR
opt_scop LIKE '%古村镇%' OR
opt_scop LIKE '%陵园%' OR
opt_scop LIKE '%纪念馆%' OR
opt_scop LIKE '%教育基地%' OR
opt_scop LIKE '%海滩%' OR
opt_scop LIKE '%歌舞厅%' OR
opt_scop LIKE '%KTV%' OR
opt_scop LIKE '%剧院%' OR
opt_scop LIKE '%戏剧%' OR
opt_scop LIKE '%游艺%' OR
opt_scop LIKE '%手工艺%' OR
opt_scop LIKE '%民俗%' OR
opt_scop LIKE '%按摩%' OR
opt_scop LIKE '%足疗%' OR
opt_scop LIKE '%疗养%' OR
opt_scop LIKE '%康复%' OR
opt_scop LIKE '%保龄球%' OR
opt_scop LIKE '%棋牌%' OR
opt_scop LIKE '%免税店%' OR
opt_scop LIKE '%签证%' OR
opt_scop LIKE '%护照%' OR
opt_scop LIKE '%外汇%' OR
opt_scop LIKE '%赛事%'
